FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

# Add migration commands before running the server
CMD python manage.py makemigrations && python manage.py migrate && gunicorn trackit_backend.wsgi:application --bind 0.0.0.0:8000